export interface MenuApiModel {
       ID: number,
        MenuText: string,
        MenuValue: string,
        UrlID: string,
        Url: string | null,
        IsFinanceRef: boolean,
        RefPageID: string | null,
        MenuOrder: string,
        VoucherID: number | null,
        Active: boolean,
        ModuleID: string,
        ParentID: number | null,
        IsPage: boolean,
        MenuLevel: number,
        MenuPermission: string | null,
        PageTitle: string | null,
        HelpID: number,
        AssemblyName: string | null,
        FormName:string | null,
        IsMaximized: string | null,
        MDIParent: string | null,
        FrequentlyUsed: boolean,
        ShortcutKey: string | null,
        ArabicName: string,
        ProcedureName: string | null
}